title: ICS4U Portfolio - Salim Hadi Salim
theme: minima
author: salimhs (github)
email: shadi2@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is an abundance of modules and such of things i've done throughout the timespan of this course.

# social links
twitter_username: shadi2
github_username:  shadi2

show_excerpts: false
